src/Entity/Participation.php
<?php

namespace App\Entity;

use App\Repository\ParticipationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ParticipationRepository::class)]
class Participation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $participation_date = null;

    #[ORM\ManyToOne(inversedBy: 'participations')]
    private ?Project $project = null;

    #[ORM\ManyToOne(inversedBy: 'participations')]
    private ?Person $donator = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getParticipationDate(): ?\DateTimeInterface
    {
        return $this->participation_date;
    }

    public function setParticipationDate(\DateTimeInterface $participation_date): static
    {
        $this->participation_date = $participation_date;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): static
    {
        $this->project = $project;

        return $this;
    }

    public function getDonator(): ?Person
    {
        return $this->donator;
    }

    public function setDonator(?Person $donator): static
    {
        $this->donator = $donator;

        return $this;
    }
}

src/Form/ParticipationType.php
<?php

namespace App\Form;

use App\Entity\Participation;
use App\Entity\Person;
use App\Entity\Project;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParticipationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('amount')
            ->add('participation_date', null, [
                'widget' => 'single_text',
            ])
            ->add('project', EntityType::class, [
                'class' => Project::class,
                'choice_label' => 'id',
            ])
            ->add('donator', EntityType::class, [
                'class' => Person::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Participation::class,
        ]);
    }
}

src/Controller/ParticipationController.php
<?php

namespace App\Controller;

use App\Entity\Participation;
use App\Form\ParticipationType;
use App\Repository\ParticipationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/participation')]
final class ParticipationController extends AbstractController
{
    #[Route(name: 'app_participation_index', methods: ['GET'])]
    public function index(ParticipationRepository $participationRepository): Response
    {
        return $this->render('participation/index.html.twig', [
            'participations' => $participationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_participation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $participation = new Participation();
        $form = $this->createForm(ParticipationType::class, $participation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($participation);
            $entityManager->flush();

            return $this->redirectToRoute('app_participation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('participation/new.html.twig', [
            'participation' => $participation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_participation_show', methods: ['GET'])]
    public function show(Participation $participation): Response
    {
        return $this->render('participation/show.html.twig', [
            'participation' => $participation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_participation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Participation $participation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ParticipationType::class, $participation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_participation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('participation/edit.html.twig', [
            'participation' => $participation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_participation_delete', methods: ['POST'])]
    public function delete(Request $request, Participation $participation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participation->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($participation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_participation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/participation/_delete_form.html.twig
<form method="post" action="{{ path('app_participation_delete', {'id': participation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/participation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/participation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Participation{% endblock %}

{% block main %}
    <h1>Edit Participation</h1>

    {{ include('participation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_participation_index') }}">back to list</a>

    {{ include('participation/_delete_form.html.twig') }}
{% endblock %}

templates/participation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participation index{% endblock %}

{% block main %}
    <h1>Participation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Amount</th>
                <th>Participation_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participation in participations %}
            <tr>
                <td>{{ participation.id }}</td>
                <td>{{ participation.amount }}</td>
                <td>{{ participation.participationDate ? participation.participationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_participation_show', {'id': participation.id}) }}">show</a>
                    <a href="{{ path('app_participation_edit', {'id': participation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_participation_new') }}">Create new</a>
{% endblock %}

templates/participation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Participation{% endblock %}

{% block main %}
    <h1>Create new Participation</h1>

    {{ include('participation/_form.html.twig') }}

    <a href="{{ path('app_participation_index') }}">back to list</a>
{% endblock %}

templates/participation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participation{% endblock %}

{% block main %}
    <h1>Participation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participation.id }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ participation.amount }}</td>
            </tr>
            <tr>
                <th>Participation_date</th>
                <td>{{ participation.participationDate ? participation.participationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_participation_index') }}">back to list</a>

    <a href="{{ path('app_participation_edit', {'id': participation.id}) }}">edit</a>

    {{ include('participation/_delete_form.html.twig') }}
{% endblock %}